---
# tasks file for assembly
- name: Clone a github repository
  git:
   repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
   dest: {{dest_folder}}
   clone: yes
   update: yes

- name: Get Boxfuse artifact from Maven
  shell: "mvn packages"
  args:
   chdir: {{dest_folder}}
